
'''
A=92
type(A)
print(str(A))
print(type(str(A)))


print(type(int("43")))


easy_as =[1,2,3]
print(easy_as)
empty=[]
letters=['a','b','c','d']
number=[2,3,4]
print(empty)
print(letters)
print(number)


mixed= [2,3,"anjali"]


print(mixed)


a=[1,2,3]
a.append(4)
print(a)


print(a[0])
print(a[-1])
letter=['a','b','c','d']

print(letter[:3])

'''

Number=[1,2,3,4,5]
Alphabet=[a,b,c,d,e]

Nested_list=[Number,Alphabet]
print(Nested_list)


'''

C:\Users\Hp\AppData\Local\Programs\Python\Python36

kjljijo

'''
